name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3

    - name: Install dependencies
      run: go install github.com/piranha/gostatic@latest
      
    - name: Build website
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        make
    - uses: actions/upload-artifact@v3
      with: 
        name: website
        path: site/
